development:
  adapter: postgresql
  encoding: unicode
  database: lost_and_found_development
  host: localhost
  port: 5432
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: lost_and_found_test
  host: localhost
  port: 5432
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: lost_and_found
  pool: 5
